dz_9-csort-loops
VolgaTat/dz-Main-JS pull request #2
Opened 2024-03-11 15:42 UTC by VolgaTat

2024-03-11 18:03 UTC, GitEsense requested changes
Отправил на небольшие доработки, в целом всё отлично, но давайте оптимизируем и немного поправим "логику" и переиспользование

2024-03-11 18:03 UTC, GitEsense commented on dz_7-converter.js
> +}
Всё вроде бы ничего, только тут не хватает немного логики, в данной реализации идёт конвертация либо с любой валюты в рубль, либо с рубля в другую валюту, а если например передать доллар и евро?
Так же функция принимает слишком много аргументов, на вход должно идти 3 аргумента (сумма (количество), входящая валюта, исходящая валюта)

Данная функция будет выглядеть лучше, если например у нас будет switch case, или else if,
например:
```js
switch(currency){
   case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                   // Логика
                   break;
                case 'EUR':
                   // Логика
                   break;
                default:
                    return null;
            }
   //   ...
}
```
И на входе 
```js
const convertResult = converter(1500, "EUR", "USD");
console.log(convertResult);    //  1666.66666666...
```

2024-03-11 18:03 UTC, GitEsense commented on dz_8-crypto.js
> +}
Эта функция несколько ломает принцип работы crypt \ decrypt
Если рассмотреть эту функцию, по сути она должна провести проверку соответствия пароля до конвертации и после, например:
```js
function checkPassword(cryptoString, password) {
   if(!password || !cryptoString) {
       return false;
   }
    return password === encryptPassword(cryptoString);
}
```
А вот логика криптографии уже в функции криптографии, если мы сделаем двойной вызов или рассмотрим функцию "decryptPassword" (если не предусмотрена обратная конвертация в первой):
```js
   const codeValue = transformPassword('password');    // ssapdorw
   const decodeValue = transformPassword(codeValue )   // password
```

2024-03-11 18:03 UTC, GitEsense commented on dz_9-sort-loops.js
> +}
Всё отлично, только есть одна проблема.
Данная функция решает задачу сортировки, но она так же модифицирует исходный массив.
Что будет, если вывести в консоль 
```js
console.log(arr)
console.log(sort(arr))
```
Надо сделать функцию sort, чтобы она не модифицировала исходный массив, но возвращала отсортированный и результат вывода в консоль тогда будет следующий

```js
console.log(arr)               // [ 1, 40, -5, 10, 0 ]
console.log(sort(arr))      // [ -5, 0, 1, 10, 40 ]
```

2024-03-11 18:03 UTC, GitEsense commented on dz_9-sort-loops.js
> +    for (let j = 0; j < arrNew.length - i; j++) {
А в этой части для сокращения количества итераций - можно во вложенном цикле сделать приравнивание **j** к **i** , например:
```js
for (let i = 0; i < arrNew.length; i++) {
        for (let j = i; j < arrNew.length; j++) {
            if (arrNew[i] > arrNew[j]) {
                [arrNew[i], arrNew[j]] = [arrNew[j], arrNew[i]];
            }
        }
```

2024-03-12 05:39 UTC, VolgaTat commented on dz_9-sort-loops.js
> +}
Алексей. но по условию задачи как раз просят решить без применения функции sort  через вложенный цикл

2024-03-12 05:42 UTC, VolgaTat commented on dz_9-sort-loops.js
> +    for (let j = 0; j < arrNew.length - i; j++) {
Объясните пожалуйста почему кол-во итераций сокращается  не могу понять

2024-03-12 05:45 UTC, VolgaTat commented on dz_7-converter.js
> +}
Не внимательно задачу прослушала,  перепишу

2024-03-12 05:59 UTC, VolgaTat commented on dz_8-crypto.js
> +}
Алексей, извините, но я не понимаю, что мне надо делать

2024-03-12 07:54 UTC, GitEsense commented on dz_8-crypto.js
> +}
> Алексей, извините, но я не понимаю, что мне надо делать

Напишите мне в телеграмме, так будет немного проще
@kld_ch_a ник

2024-03-15 10:45 UTC, GitEsense reviewed
Всё отлично, всё работает, всё окей, но давайте чуток оптимизируем и наведём немного красоты

2024-03-15 10:45 UTC, GitEsense commented on dz_7-converter.js
> +console.log(converter(10, "USDTY", "EUR"));
Достаточно было бы сделать
const USD = 91.33
const EUR = 112.33
const RUB = 1

Тогда при расчёте USD to EUR можно было бы воспользоваться
sum * currency (USD) / targetCurrency(EUR)
и запись этого вида
```js
switch(currency){ 
    case 'USD':
      switch (targetCurrency) { 
          case 'RUB':
            result = Math.ceil(sum * courseUSDinRUB) + " руб";
            break;
          case 'EUR':
            result = Math.ceil(sum * courseUSDinEUR) + " €";
            break;
          default:
            return null;
      }
    break;
  }
```
Могла бы выглядеть универсальнее
```js
switch(currency){ 
    case 'USD':
      switch (targetCurrency) { 
          case 'RUB':
            result = (sum * USD) + " руб";
            break;
          case 'EUR':
            result = Math.ceil(sum * USD / EUR) + " €";
            break;
          default:
            return null;
      }
    break;
  }
```
или для пущей красоты
сделать функцию

```js
function convertSum(sum, from, to){
   return Math.ceil(sum * from / to)
}

switch(currency){ 
    case 'USD':
      switch (targetCurrency) { 
          case 'RUB':
            return convertSum(sum, USD, RUB) + " руб";
            break;
          case 'EUR':
            return convertSum(sum, USD, EUR)  + " €";
            break;
          default:
            return null;
      }
    break;
  }

```
Так же у Вас тройной switch для currency, а оно работает немного не так, можно было бы под один switch(currency) положить всю логику валют и дать default

Вот такой пример я имел ввиду
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function converter(sum, currency, targetCurrency) {
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return convertSum(sum, USD, RUB) + ' руб';
                case 'EUR':
                    return convertSum(sum, USD, EUR) + ' €';
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return convertSum(sum, RUB, USD) + ' $';
                case 'EUR':
                    return convertSum(sum, RUB, EUR) + ' €';
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return convertSum(sum, EUR, RUB) + ' руб';
                case 'USD':
                    return convertSum(sum, EUR, USD) + ' $';
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }
        default: {
            console.log('Входящая валюта мне неизвестна');
            return null;
        }
    }
}


console.log(converter(100, 'RUB', 'USD'));      // 1.09 $
console.log(converter(100, 'RUB', 'EUR'));      // 0.89 €
console.log(converter(1000, 'EUR', 'USD'));     // 1229.94 $
console.log(converter(1000, 'USD', 'EUR'));     // 813.05 €
console.log(converter(1000, 'EUR', 'RUB'));     // 112330.00 руб

console.log(converter(1500, "EUR", "RUB"));
console.log(converter(1500, "USD", "RUB"));

console.log(converter(10, "RUB", "EUR"));
console.log(converter(10, "USD", "EUR"));

console.log(converter(10, "RUB", "EURU"));
console.log(converter(10, "USD", "EUR"));

console.log(converter(10, "RUB", "EUR"));
console.log(converter(10, "USDTY", "EUR"));
```

2024-03-15 10:45 UTC, GitEsense commented on dz_8-crypto.js
>      const nemPassword = `${removePartEnd.join("")}${smashPassword.join("")}`;
Можно было бы записать что-то вроде
```js
const nemPassword = [...removePartEnd, ...smashPassword].join('')
```

2024-03-15 10:45 UTC, GitEsense commented on dz_9-sort-loops.js
> +        arr[j] = tempVariable;
можно воспользоваться трюком обмена переменными, вот тут почитать можно
https://learn.javascript.ru/destructuring-assignment

Вы его уже применяли ниже)

2024-03-15 10:45 UTC, GitEsense commented on dz_9-sort-loops.js
> +// console.log(assortArray([-2, 0, -45, -10, -245]));
А вот с этими функциями вопрос, т.к. они по прежнему модифицируют исходный массив
```js
const array = [1, 40, -5, 10, 0];
let count = 0;
const assortArray = (arr) => {
    for (let i = 0; i < arr.length; i++) {
        for (let j = i + 1; j < arr.length; j++) {
            if (arr[i] > arr[j]) {
                let tempVariable = arr[i];
                arr[i] = arr[j];
                arr[j] = tempVariable;
            }
            count++;
            console.log(`Итерации: i: ${i} - j: ${j}, общее кол-во: ${count}`);
        }
    }
    return arr;
};
console.log(assortArray(array));    //  [ -5, 0, 1, 10, 40 ]
console.log(array);                 //  [ -5, 0, 1, 10, 40 ] а должно быть [1, 40, -5, 10, 0]
```

Поменяйте функцию так, чтобы не было модификации массива

2024-03-18 08:01 UTC, GitEsense approved these changes
Всё отлично, можно мерджить и двигаться дальше)

2024-03-18 08:01 UTC, GitEsense commented on dz_9-sort-loops.js
> +return newArray;
Тут всё же "симпатичнее" была бы запись
```js
const arr = [1, 40, -5, -10, 0];
const assortArray = (array) => {
    const newArray = [...array];
    for (let i = 0; i < newArray.length; i++) {
        for (let j = i + 1; j < newArray.length; j++) {
            if (newArray[i] > newArray[j]) {
                [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
            }
        }
    }
    return newArray;
};

```

2024-03-26 11:16 UTC, merged