Code review 3
VolgaTat/dz-Main-JS pull request #3
Opened 2024-03-26 11:23 UTC by VolgaTat

2024-03-26 13:34 UTC, GitEsense requested changes
`dz_10-array-clean.js` `dz_12-luna.js` - всё Ок!
`dz_11-date-array.js` - нужно переделать

2024-03-26 13:34 UTC, GitEsense commented on dz_10-array-clean.js
> +console.log(arr);
Решение довольно интересное, но очень запутанное, не говоря уже о  том, что resultArray у Вас объявляется в начале функции, затем возвращается функция, которая наполняет результирующий массив (не со своей области видимости, но от родительской).
Имеет право на жизнь и выполняет задачу, однако, можно было бы оптимизировать и сделать сильно красивее)

В данной реализации мы передаём конкретную функцию, которая содержит в себе условия проверки чисел, при этом не трогая функционал исходной функции (filterArray), тем самым какой бы массив ни был, какое бы условие ни было - функция будет делать то же самое
```js
const arr = [-200, -22, -52, 10, 22, 35, 44, 15, 3, 7, 37, 69, 82, 55, 65, 72, 18, 4, 92];

//  Функция фильтрации
function filterArray(array, fn) {
    const resultArray = [];
    for (let i = 0; i < array.length; i++) {
        const isDelete = fn(array[i]); //  Вызываем функцию, результатом которой будет необходимость удалить число, где true - да, false - нет
        if (!isDelete) {
            //  Если оставить, то кладём в результирующий массив
            resultArray.push(array[i]);
        }
    }
    return resultArray;
}

/* Функция условия удаления 
    Условие: 
    Если число больше двух, но меньше 5
    или равно 7 
    или больше 50, но остаток от деления на 5 равен 0 (55, 60, 65 и т.п.)
    или остаток от деления на 4 равен 0 (4, 8, 16, 32, 64 и т.п.)
    или остаток от деления на 11 равен 2 (13, 24, 35 и т.п.)
*/
function canDelete(num) {
    return (num > 2 && num < 5) || num === 7 || (num > 50 && num % 5 === 0) || num % 4 === 0 || num % 11 === 2;
}

function canDelete2(num) {
    return num < 5;
}

function canDelete3(num) {
    return num > 5 || num < 0;
}

function canDelete4(num) {
    return (num > 33 && num < 66) || num < 0;
}

const result1 = filterArray(arr, canDelete);
const result2 = filterArray(arr, canDelete2);
const result3 = filterArray(arr, canDelete3);
const result4 = filterArray(arr, canDelete4);

console.log(result1);   //  [ -22, 10, 22, 15, 37, 69, 82, 18 ]
console.log(result2);   //  [ 10, 22, 35, 44, 15, 7, 37, 69, 82, 55, 65, 72, 18, 92 ]
console.log(result3);   //  [ 3, 4 ]
console.log(result4);   //  [ 10, 22, 15, 3, 7, 69, 82, 72, 18, 4, 92 ]
```

2024-03-26 13:34 UTC, GitEsense commented on dz_11-date-array.js
> +console.log(filterDateStr(dateArrayStr));
Так же интересное решение, но... оно усложнено и никак не валидируется, кроме фильтрации, так же не отвечает задаче.
Дата у нас приходит строкой в формате 
"10-02-2022" = RU-формат "дд-мм-гггг", т.е. 10 февраля 2022 года
"10/02/2022" = EN-формат "мм-дд-гггг", т.е. 2 октября 2022 года

Задача состоит из трёх этапов:
1. Разобрать строку на массив [день, месяц, год]
2. Проверить строку на соответствие
3. Вернуть строку в RU формате (дд-мм-гггг)

2024-03-26 13:34 UTC, GitEsense commented on dz_12-luna.js
> +}
Всё отлично, но добавим немного "изящности"
```js
function cardLunaValidate(card) {
    const cardNumber = card
        .replaceAll('-', '')
        .split('')
        .map((x) => Number(x));
    if (cardNumber.includes(NaN)) {
        return NaN;
    }
    const isEven = (cardNumber.length - 1) % 2 === 0;
    for (let i = Number(isEven); i < cardNumber.length; i = i + 2) {
        cardNumber[i] = cardNumber[i] * 2 > 9 ? cardNumber[i] * 2 - 9 : cardNumber[i] * 2;
    }
    const sum = cardNumber.reduce((total, el) => total + el);
    return sum % 10 === 0;
}
```

```js
function resultTemplate(card) {
    const startString = `Карта с номером: ${card}`;
    const endString = `получила результат: ${cardLunaValidate(card)}`;
    return `${startString} ${endString}`;
}
```

```js
const card = '234s834503458353';
const card1 = '2342834503458353';
const card2 = '4561-2612-1234-548';
const card3 = '4561-2612-1534-5464';

console.log(resultTemplate(card));
console.log(resultTemplate(card1));
console.log(resultTemplate(card2));
console.log(resultTemplate(card3));
```

2024-03-27 09:18 UTC, VolgaTat commented on dz_11-date-array.js
> +console.log(filterDateStr(dateArrayStr));
Переделаю

2024-03-27 09:22 UTC, VolgaTat commented on dz_12-luna.js
> +}
Алексей, действительно у вас красивый код.
Нигде не видела, что можно так делать const isEven = (cardNumber.length - 1) % 2 === 0; - запомню

2024-03-27 09:44 UTC, VolgaTat commented on dz_10-array-clean.js
> +console.log(arr);
Ну, для новичков я считаю тема не совсем простая, поэтому, как раз и никак не могла сообразить, как передать проверку условия через функцию. Прекрасно понимала, что условия могут быть разные.

2024-03-27 09:57 UTC, GitEsense commented on dz_10-array-clean.js
> +console.log(arr);
> Ну, для новичков я считаю тема не совсем простая, поэтому, как раз и никак не могла сообразить, как передать проверку условия через функцию. Прекрасно понимала, что условия могут быть разные.

Ну тут как раз пример функции высшего порядка, которая получает на вход функцию условий, в Вашем же случае принцип функции высшего порядка сохранён, т.к. функция возвращает функцию, но тут теряется гибкость, следовательно передать функцию и разумнее в данном случае

2024-04-01 07:59 UTC, GitEsense approved these changes
В целом всё ок, но как-то прям слишком всё усложнено))
Так же у Вас функция filterDateStr() не принимает массив, а берёт объявленный ранее, лучше передавать в неё массив, с которым будем работать (точнее на основе которого) и уже идти дальше.
Ну а так же как и обещал предлагаю свой вариант на ознакомление ))

```js
//  Домашнее задание
/*
    Дан массив строк ['10-02-2022','тест','11/12/2023','00/13/2022','41/12/2023'];
    Необходимо написать функцию, которая удаляла бы из массива все строки, которые нельзя перевести в дату
    (можно: 10-02-2022 и 11/12/2023) и возвращала новый массив вида:
    -   ['10-02-2022','12-11-2023']
*/
const length = 30;

//   Создаём динамически даты для простоты эксперимента
const inputDates = Array.from({ length }, () => {
    function randomNumber(min = 0, max = 35) {
        return Math.ceil(Math.random() * (max - min)) + min;
    }

    const factor = Math.random() > 0.5 ? '/' : '-';

    const dateArray = [randomNumber(), randomNumber(), randomNumber(1900, 2050)].map((x) => x.toString().padStart(2, '0'));
    return dateArray.join(factor);
});

//   Функция получения отфильтрованного массива (принимает массив дат и условие фильтрации)
function getDates(array, fn) {
    return array.map(stringToArray).filter(fn).sort(sortDatePattern).map(formatDate);
}

//   Функция форматирования даты для "единообразного" вывода
function formatDate(array) {
    return array.map((x, i) => (i === 2 ? x.padStart('0', 4) : x.padStart('0', 2))).join('-');
}

//   Функция сортировки дат (для красоты вывода)
function sortDatePattern(a, b) {
    let day, month, year;

    [day, month, year] = a;
    const dt1 = new Date(year, month - 1, day).getTime();

    [day, month, year] = b;
    const dt2 = new Date(year, month - 1, day).getTime();

    return dt1 - dt2;
}

//   Функция конвертации строки даты в массив
function stringToArray(str) {
    let day, month, year;
    if (str.includes('/')) {
        [month, day, year] = str.split('/');
    } else if (str.includes('-')) {
        [day, month, year] = str.split('-');
    }
    if (!year || isNaN(day) || isNaN(month) || isNaN(year)) {
        return null;
    }
    return [day, month, year];
}

//   Функция условий фильтрации (проверка даты на валидность)
function checkCorrectDate(array) {
    if (array === null) {
        return false;
    }

    [day, month, year] = array.map(Number);

    const LONG_MONTH_ARRAY = [1, 3, 5, 7, 8, 10, 12];

    const isLeapYear = (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;

    // check month
    if (month < 1 || month > 12 || year <= 0) {
        return false;
    }

    // check day
    if (day < 1 || day > 31) {
        return false;
    }

    if (day === 31 && !LONG_MONTH_ARRAY.includes(month)) {
        return false;
    }

    // check February for correct day and leap year
    if (month === 2 && day === 29 && !isLeapYear) {
        return false;
    }
    return true;
}

const res = getDates(inputDates, checkCorrectDate);
console.log(inputDates);
console.log(res);
```

2024-04-02 15:04 UTC, merged